apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service_account.yaml

# The image reference below is what the `publish-kustomize-bundle` reusable
# workflow patches on release to pin the bundle against a specific container
# image digest.
images:
  - name: ghcr.io/milo-os/amberflo-provider
    newTag: latest

configMapGenerator:
  - files:
      - config.yaml
    name: amberflo-provider-config
    options:
      disableNameSuffixHash: true
