apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amberflo-provider-system

resources:
  - namespace.yaml
  - ../../base/manager

components:
  - ../../components/leader_election

configMapGenerator:
  - name: amberflo-provider-config
    behavior: replace
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: amberflo-provider
    path: deployment_patch.yaml
